src/routes/home.py
from flask import Blueprint, render_template

bp: Blueprint = Blueprint("home", __name__)


@bp.route("/")
def home() -> str:
    return render_template("home.html.jinja")

src/templates/album.html.jinja
{% extends "base.html.jinja" %}
{% from "macros.html.jinja" import icon %}
{% from "context_macros.html.jinja" import navigation_buttons with context %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='album.css') }}" />
{% endblock head %}

{% block content %}
    <div id="album">
        {% for i in items %}
            <div class="album_item">
                {% if type(i) == "Photo" %}
                    <a href="{{ url_for('posts.photo', fbid=i.id) }}">
                        <img src="{{ i.url | proxy }}" />
                    </a>
                {% else %}
                    <a href="{{ url_for('posts.videos', author=i.owner_id, token=i.id) }}">
                        <img src="{{ i.thumbnail_url | proxy }}" />{{ icon("play") }}
                    </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    {{ navigation_buttons() }}
{% endblock content %}

src/templates/base.html.jinja
{% from "macros.html.jinja" import icon %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% set theme = request.cookies.get("theme") %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{{ title + " | " if title }}Phice</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
        {% if theme == "light" %}
            <link rel="stylesheet" href="{{ url_for('static', filename='themes/light.css') }}" />
        {% elif theme == "black" %}
            <link rel="stylesheet" href="{{ url_for('static', filename='themes/black.css') }}" />
        {% elif theme == "catppuccin_mocha" %}
            <link rel="stylesheet" href="{{ url_for('static', filename='themes/catppuccin_mocha.css') }}" />
        {% elif theme == "catppuccin_latte" %}
            <link rel="stylesheet" href="{{ url_for('static', filename='themes/catppuccin_latte.css') }}" />
        {% endif %}
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}" />
        <meta property="og:title" content="{{ title }}" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="{{ url_for('static', filename='favicon.png') }}" />
        <meta property="og:url" content="{{ request.base_url }}" />
        <meta property="og:description" content="A lightweight privacy-friendly alternative front-end for Facebook" />
        <meta property="og:site_name" content="Phice" />
        {% if config["ENABLE_RSS"] and request.endpoint in ("profile.profile", "groups.groups") %}
            <link rel="alternate" type="application/rss+xml" href="?rss=1" title="RSS Feed">
        {% endif %}
        {% block head %}{% endblock head %}
    </head>
    <body>
        <header>
            <a class="no_underline" href="{{ url_for('home.home') }}">
                <svg id="header_logo" class="logo"><use href="{{ url_for('static', filename='logo.svg') }}#logo"></use></svg>
                <span id="name">Phice</span>
            </a>
            <div id="header_buttons">
                <a href="{{ url_for('home.home') }}">{{ icon("search") }}</a>
                {% if config["ENABLE_RSS"] and request.endpoint in ("profile.profile", "groups.groups") %}
                    <a href="?rss=1">{{ icon("rss") }}</a>
                {% endif %}
                <a href="{{ 'https://facebook.com' + request.full_path }}">{{ icon("facebook") }}</a>
                <a href="{{ url_for('settings.settings') }}">{{ icon("gear") }}</a>
            </div>
        </header>
        <main>
            {% block content %}{% endblock content %}
        </main>
    </body>
</html>

src/templates/context_macros.html.jinja
{% from "macros.html.jinja" import icon %}

{% macro navigation_buttons() -%}
    <div id="navigation_buttons">
        {% if request.args.get("cursor") %}
            <a
                class="a_button"
                href="{{ url_for(request.endpoint, **dict(request.view_args | items | list + request.args | items | rejectattr("0", "eq", "cursor") | list)) }}"
            >{{ icon("angles-left") }}Start</a>
        {% endif %}
        {% if has_next -%}
            <a
                class="a_button"
                href="{{ url_for(request.endpoint, **dict(request.view_args | items | list + request.args | items | list, cursor=cursor)) }}"
            >Next{{ icon("chevron-right") }}</a>
        {%- endif %}
    </div>
{%- endmacro %}

src/templates/error.html.jinja
{% extends "base.html.jinja" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='error.css') }}" />
{% endblock head %}

{% block content %}
    <div id="whole_screen">
        <div id="error_message">
            <h1>Error {{ e.code }}</h1>
            <p>{{ e.description }}</p>
        </div>
    </div>
{% endblock content %}

src/templates/home.html.jinja
{% extends "base.html.jinja" %}
{% from "macros.html.jinja" import icon, search_bar %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}" />
{% endblock head %}

{% block content %}
    <div id="whole_screen">
        <div class="home_logo">
            <svg class="logo"><use href="{{ url_for('static', filename='logo.svg') }}#logo"></use></svg>
            <span>Phice</span>
        </div>
        {{ search_bar() }}
    </div>
{% endblock content %}

src/templates/post.html.jinja
{% extends "base.html.jinja" %}
{% from "macros.html.jinja" import icon, Comment, Post %}
{% from "context_macros.html.jinja" import navigation_buttons with context %}

{% block content %}
    {{ Post(post, expanded=true) }}
    {%- if post.feedback_id is not none %}
        <section class="comment_section">
            <form id="comment_sort_form">
                {% if request.args.get("comment_id") %}
                    <input type="hidden" name="comment_id" value="{{ request.args.comment_id }}" />
                {% endif %}
                <select name="sort">
                    {% set sort = request.args.get("sort") or request.cookies.get("comments_sort") %}
                    <option value="filtered">Most relevant</option>
                    <option value="newest" {{ "selected" if sort == "newest" }}>Newest</option>
                    <option value="all" {{ "selected" if sort == "all" }}>All</option>
                </select>
                <button type="submit" class="icon_button">{{ icon("chevron-right") }}</button>
            </form>
            {% if comments %}
                {% for i in comments %}
                    {{ Comment(i, "reply" if i.is_reply else "") }}
                {% endfor %}
            {% else %}
                <span class="card centered">No comments.</span>
            {% endif %}
            {{ navigation_buttons() }}
        </section>
    {% endif %}
{% endblock content %}

src/templates/search.html.jinja
{% extends "base.html.jinja" %}
{% from "macros.html.jinja" import icon, Post, search_bar %}
{% from "context_macros.html.jinja" import navigation_buttons with context %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='search.css') }}" />
{% endblock head %}

{% block content %}
    {{ search_bar() }}
    {% for i in results %}
        {% if type(i) == "User" %}
            <a class="no_underline" href="{{ url_for('profile.profile', username=i.username) }}">
                <div class="search_card card">
                    <img class="search_card_picture" src="{{ i.picture_url | proxy }}" alt="{{ i.name }}'s profile picture" />
                    <div class="search_body">
                        <span>{{ i["name"] }}</span>{{ icon("circle-check", class="profile_checkmark") if i.verified }}
                        <p class="search_card_description">{{ i.description or "" }}</p>
                    </div>
                </div>
            </a>
        {% elif type(i) == "Post" %}
            {{ Post(i) }}
        {% endif %}
    {% endfor %}
    {{ navigation_buttons() }}
{% endblock content %}

src/templates/settings.html.jinja
{% extends "base.html.jinja" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='settings.css') }}" />
{% endblock head %}

{% macro get(option, value, attr) -%}
    {{ attr if request.cookies.get(option, config["DEFAULT_SETTINGS"].get(option)) == value }}
{%- endmacro %}

{% block content %}
    <form id="settings" method="post">
        <h1>Settings:</h1>
        <input type="hidden" name="referrer" value="{{ request.headers.get('referer', '') }}" />
        <label class="settings_row">
            Theme
            <select name="theme">
                <option value="default">Default</option>
                <option value="light" {{ get("theme", "light", "selected") }}>Light</option>
                <option value="black" {{ get("theme", "black", "selected") }}>Black</option>
                <option value="catppuccin_mocha" {{ get("theme", "catppuccin_mocha", "selected") }}>Catppuccin mocha</option>
                <option value="catppuccin_latte" {{ get("theme", "catppuccin_latte", "selected") }}>Catppuccin latte</option>
            </select>
        </label>
        <label class="settings_row">
            Proxy media
            <input type="checkbox" name="proxy" {{ get("proxy", "on", "checked") }} />
        </label>
        <label class="settings_row">
            Default comments sort
            <select name="comments_sort">
                <option value="filtered" {{ get("comments_sort", "filtered", "selected") }}>Most relevant</option>
                <option value="newest" {{ get("comments_sort", "newest", "selected") }}>Newest</option>
                <option value="all" {{ get("comments_sort", "all", "selected") }}>All</option>
            </select>
        </label>
        <label class="settings_row">
            Expand posts
            <input type="checkbox" name="expand" {{ get("expand", "on", "checked") }} />
        </label>
        <hr />
        <div class="settings_footer">
            <button type="submit" name="save" value="on">Save</button>
            <button type="submit" name="reset" value="on">Reset</button>
        </div>
    </form>
{% endblock content %}

src/templates/timeline.html.jinja
{% extends "base.html.jinja" %}
{% from "macros.html.jinja" import icon, Post, expandable_p %}
{% from "context_macros.html.jinja" import navigation_buttons with context %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='timeline.css') }}" />
{% endblock head %}

{% block content %}
    <div id="timeline_cover">
        {% if info.cover_url %}
            <img src="{{ info.cover_url | proxy }}" alt="{{ info.name }}'s profile cover" />
        {% endif %}
    </div>
    <div id="timeline">
        <section id="timeline_info" class="card">
            <div id="timeline_header">
                {% if not info.is_group %}
                    <img id="timeline_picture" src="{{ info.picture_url | proxy }}" alt="{{ info.name }}'s profile picture" />
                {% endif %}
                <div>
                    <span class="profile_name">{{ info.name }}</span>{{
                        icon("circle-check", class="profile_checkmark") if info.verified
                    }}
                    <br />
                    <span id="timeline_stat">{{ info.members + " Members" if info.members }}{{
                        info.followers + " Followers" if info.followers
                    }}{{ " • " + info.following + " Following" if info.following }}{{
                        " • " + info.likes + " Likes" if info.likes
                    }}</span>
                </div>
            </div>
            <div id="timeline_intro">
                {{ expandable_p(info.description, class="timeline_description") if info.description }}
                {% if info.info %}
                    <hr />
                    {% for i in info.info %}
                        <a {% if i.url %}href="{{ i.url }}"{% endif %}>
                            <div class="timeline_info_cards">
                                {%- if i.type == "website" -%}
                                    {{ icon("link") }}
                                {%- elif i.type in ("address", "hometown", "current_city") -%}
                                    {{ icon("location") }}
                                {%- elif i.type == "phone" -%}
                                    {{ icon("phone") }}
                                {%- elif i.type == "work" -%}
                                    {{ icon("briefcase") }}
                                {%- elif i.type == "education" -%}
                                    {{ icon("user-graduate") }}
                                {%- elif i.type == "business_hours" -%}
                                    {{ icon("clock") }}
                                {%- elif i.type == "profile_email" -%}
                                    {{ icon("email") }}
                                {%- else -%}
                                    {{ icon("circle-info") }}
                                {%- endif -%}
                                <span>{{ i.text }}</span>
                            </div>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        </section>
        <section id="timeline_feed">
            {% if info.is_private %}
                <span class="card centered">{{ icon("lock") }} The content is private.</span>
            {% elif posts %}
                {% for i in posts %}
                    {{ Post(i, expanded=request.cookies.get("expand") == "on") }}
                {% endfor %}
                {{ navigation_buttons() }}
            {% else %}
                <span class="card centered">No posts.</span>
            {% endif %}
        </section>
    </div>
{% endblock content %}

src/templates/timeline.rss.jinja
<?xml version="1.0"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
    <channel>
        <title>{{ info.name }} | Phice</title>
        <link>{{ url_for("groups.groups", token=info.token, _external=true) if info.is_group else url_for("profile.profile", username=info.token, _external=true) }}</link>
        <description>RSS feed for {{ info.name }}</description>
        {% if info.picture_url -%}
            <image>
                <url>{{ info.picture_url | proxy }}</url>
                <title></title>
                <link>{{
                    url_for(
                        "groups.groups",
                        token=info.token,
                        _external=true,
                    ) if info.is_group else url_for(
                        "profile.profile",
                        username=info.token,
                        _external=true,
                    )
                }}</link>
            </image>
        {%- endif %}
        {%- for i in posts %}
        <item>
            <title>{{ i.text[:60] }} | {{ i.author.name }}</title>
            <link>{{
                url_for(
                    "posts.groups_posts",
                    author=i.from_group.username,
                    token=i.post_id,
                    _external=true,
                ) if i.from_group else url_for(
                    "posts.videos" if i.is_video else "posts.posts",
                    author=i.author.username,
                    token=i.post_id,
                    _external=true,
                )
            }}</link>
            <description>
                <![CDATA[{{ i.text }}{%- if i.attachments -%}
                    <br />
                    {%- for i in i.attachments | reverse -%}
                        <br />
                        {%- set t = type(i) -%}
                        {%- if t == "Photo" -%}
                            <img src="{{ i.url | proxy }}" alt="{{ i.alt_text }}" />
                        {%- elif t == "Video" -%}
                            <video controls src="{{ i.url | proxy }}"><a href="{{ i.url | proxy }}">Video</a></video>
                        {%- elif t == "AnimatedImage" -%}
                            <video loop autoplay muted src="{{ i.url | proxy }}"><a href="{{ i.url | proxy }}">Video</a></video>
                        {%- elif t == "Poll" -%}
                            {%- for j in i.options -%}
                                {{ j[0] ~ " " ~ j[1] ~ " " ~ j[2] ~ "%" }}<br />
                            {%- endfor -%}
                        {%- elif t == "Unavailable" -%}
                            This content isn't available right now
                        {%- elif t == "Event" -%}
                            {{ i.name }}<br />{{ i.time }}<br />{{ i.description }}
                        {%- endif -%}
                    {%- endfor -%}
                {%- endif -%}
                <br />
                <span>Reactions: {{ i.reactions["total"] | format_number }} | Comments: {{ i.comments_count | format_number }} | Shares: {{ i.share_count | format_number }}</span>]]>
            </description>
            <author>{{ i.author.name }}</author>
            <guid>{{ i.post_id }}</guid>
            <pubDate>{{ i.time | format_time_rfc822 }}</pubDate>
        </item>
        {%- endfor %}
    </channel>
</rss>